---
fixtures:
  repositories:
    apache: "git://github.com/simp/pupmod-simp-apache"
    auditd: "git://github.com/simp/pupmod-simp-auditd"
    augeasproviders_core: "git://github.com/simp/augeasproviders_core"
    augeasproviders_grub: "git://github.com/simp/augeasproviders_grub"
    common: "git://github.com/simp/pupmod-simp-common"
    concat: "git://github.com/simp/pupmod-simp-concat"
    iptables: "git://github.com/simp/pupmod-simp-iptables"
    logrotate: "git://github.com/simp/pupmod-simp-logrotate"
    pam: "git://github.com/simp/pupmod-simp-pam"
    pki: "git://github.com/simp/pupmod-simp-pki"
    rsync: "git://github.com/simp/pupmod-simp-rsync"
    rsyslog: "git://github.com/simp/pupmod-simp-rsyslog"
    ssh: "git://github.com/simp/pupmod-simp-ssh"
    stdlib: "git://github.com/simp/puppetlabs-stdlib"
    sudo: "git://github.com/simp/pupmod-simp-sudo"
    functions: "git://github.com/simp/pupmod-simp-functions"
    simp: "git://github.com/simp/pupmod-simp-simp"
  symlinks:
    backuppc: "#{source_dir}"
